version: '3'
services:
  rabbit-mq:
    build: message-queue-server
    ports:
      - "5672:5672"
      - "15672:15672"
  proxy:
    build: proxy
    ports:
      - 3000:3000
    restart: unless-stopped
  sms-service:
    build: sms-service
    ports:
      - "7000:7000"
    depends_on:
      - rabbit-mq
    restart: unless-stopped
  frontend:
    build: frontend/messages
    ports:
      - 4200:4200